package portalPages.polls.polls;

public enum PollCategory {

    CATEGORY_ART_CULTURE("Art & Culture"),
    CATEGORY_VALUE_ART_CULTURE("24"),
    CATEGORY_ART_HISTORY("Art History"),
    CATEGORY_VALUE_ART_HISTORY("56"),
    CATEGORY_ART_ENTERTAINMENT("Art & Entertainment"),
    CATEGORY_VALUE_ART_ENTERTAINMENT("45"),
    CATEGORY_BUSINESS("Business"),
    CATEGORY_VALUE_BUSINESS("7"),
    CATEGORY_BOOKS_LITERATURE("Books & Literature"),
    CATEGORY_VALUE_BOOKS_LITERATURE("46"),
    CATEGORY_CONSUMER_PRODUCTS("Consumer products"),
    CATEGORY_VALUE_CONSUMER_PRODUCTS("23"),
    CATEGORY_ECONOMY("Economy"),
    CATEGORY_VALUE_ECONOMY("49"),
    CATEGORY_EDUCATION("Education"),
    CATEGORY_VALUE_EDUCATION("39"),
    CATEGORY_ENTERTAINMENT("Entertainment"),
    CATEGORY_VALUE_ENTERTAINMENT("5"),
    CATEGORY_FINE_ART("Fine Art"),
    CATEGORY_VALUE_FINE_ART("53"),
    CATEGORY_FOOD_DRINK("Food & Drink"),
    CATEGORY_VALUE_FOOD_DRINK("57"),
    CATEGORY_GAMES("Games"),
    CATEGORY_VALUE_GAMES("44"),
    CATEGORY_HEALTH("Health"),
    CATEGORY_VALUE_HEALTH("8"),
    CATEGORY_HOBBIES_INTERESTS("Hobbies & Interests"),
    CATEGORY_VALUE_HOBBIES_INTERESTS("60"),
    CATEGORY_HUMOR("Humor"),
    CATEGORY_VALUE_HUMOR("54"),
    CATEGORY_LIFESTYLE("Lifestyle"),
    CATEGORY_VALUE_LIFESTYLE("6"),
    CATEGORY_MAGIC_ILLUSION("Magic & Illusion"),
    CATEGORY_VALUE_MAGIC_ILLUSION("61"),
    CATEGORY_NEWS("News"),
    CATEGORY_VALUE_NEWS("37"),
    CATEGORY_POLITICS("Politics"),
    CATEGORY_VALUE_POLITICS("3"),
    CATEGORY_MOVIES("Movies"),
    CATEGORY_VALUE_MOVIES("47"),
    CATEGORY_POLITICS_POLICY("Politics & Policy"),
    CATEGORY_VALUE_POLITICS_POLICY("58"),
    CATEGORY_SPORT_IAB17("SPORT(IAB17)"),
    CATEGORY_VALUE_SPORT_IAB17("70"),
    CATEGORY_SCIENCE("Science"),
    CATEGORY_VALUE_SCIENCE("36"),
    CATEGORY_SCIENCE_X("Science X"),
    CATEGORY_VALUE_SCIENCE_X("50"),
    CATEGORY_SHOPPING("Shopping"),
    CATEGORY_VALUE_SHOPPING("52"),
    CATEGORY_SILICON_VALLEY("Silicon Valley"),
    CATEGORY_VALUE_SILICON_VALLEY("38"),
    CATEGORY_SPORT_HEALTH("Sport & Health"),
    CATEGORY_VALUE_SPORT_HEALTH("48"),
    CATEGORY_SPORTS("Sports"),
    CATEGORY_VALUE_SPORTS("12"),
    CATEGORY_TECHNOLOGY("Technology"),
    CATEGORY_VALUE_TECHNOLOGY("1"),
    CATEGORY_TELEVISION("Television"),
    CATEGORY_VALUE_TELEVISION("55"),
    CATEGORY_WORLD("World"),
    CATEGORY_VALUE_WORLD("9");

    private final String pollCategory;

    PollCategory(final String title) {
        this.pollCategory = title;
    }

    @Override
    public String toString() {
        return pollCategory;
    }
}
